version: "3.9"
services:
  web:
    image: my-app:0.1
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - server
  server:
    image: "rdb-poc-server:0.1"
    depends_on:
      - data-writer
    ports:
      - "8082:8082"
    restart: unless-stopped
  data-writer:
    image: "data-writer:0.1"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "rethinkdb"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "28015:28015"


